const fs = require("fs");
const path = require("path");
const bcrypt = require("bcryptjs");
const crypto = require("crypto");

const DATA_DIR = path.join(__dirname, "..", "data");
const DB_FILE = path.join(DATA_DIR, "optiforge_db.json");

const EXPECTED_OUTPUT_CHECKLIST = [
  "Algorithm implementation (submitted notebook/script)",
  "Parameter configuration used, clearly stated",
  "Final objective/score for each attempt",
  "Convergence or iteration evidence (a plot or log showing the algorithm improving over iterations)",
  "A short written explanation covering: representation used, operators/rules chosen, how constraints were handled, and why the selected CI technique fits this problem",
  "A one-line 'what changed and why' note with every attempt after the first",
];

async function seed() {
  console.log("Seeding OptiForge 2026 database with 9 Innovation Themes...");
  if (!fs.existsSync(DATA_DIR)) {
    fs.mkdirSync(DATA_DIR, { recursive: true });
  }

  const now = new Date().toISOString();

  // 1. Settings
  const systemSettings = [
    { key: "active_stage", value: "PRE_EVENT", description: "Current tournament stage", updatedAt: now },
    { key: "leaderboard_frozen", value: "false", description: "Freeze leaderboard updates", updatedAt: now },
    { key: "leaderboard_visible", value: "false", description: "Public visibility of leaderboard", updatedAt: now },
    { key: "live_patch_duration_mins", value: "20", description: "Duration of live patch round in minutes", updatedAt: now },
    { key: "live_patch_deadline", value: "", description: "Active countdown deadline for Stage 7 live patch", updatedAt: now },
    { key: "weight_auto", value: "60", description: "Confidential: Percentage weight of auto-score", updatedAt: now },
    { key: "weight_judge", value: "40", description: "Confidential: Percentage weight of manual judge score", updatedAt: now },
    { key: "registration_open", value: "true", description: "Allow team registrations", updatedAt: now },
    { key: "event_date", value: "30-09-2026", description: "Official event date", updatedAt: now },
    { key: "event_time", value: "9:00 AM – 4:00 PM IST", description: "Official event timing", updatedAt: now },
    { key: "organizer_entity", value: "IEEE Vardhaman Student Branch", description: "Organizing student branch", updatedAt: now },
  ];

  // 2. The Official Innovation Themes
  const problemTracks = [
    {
      id: "theme-1-biomedical-ai",
      name: "Biomedical Artificial Intelligence",
      shortName: "01: Biomedical AI",
      society: "IEEE EMBS × IEEE CIS",
      difficulty: "Advanced",
      technique: "Evolutionary Neural Architecture Search & Hybrid GA-ML",
      context: "Clinical healthcare pipelines generate vast multi-modal patient telemetry, electronic health records, genomic biomarkers, and pathology features. Medical practitioners require explainable AI models capable of predictive risk stratification while respecting strict sensitivity constraints.",
      coreChallenge: "Design an evolutionary optimization algorithm to search high-dimensional biomedical feature spaces and optimize hybrid clinical decision boundaries, maximizing sensitivity for rare critical pathologies while minimizing false positive alerts under real-world clinical noise.",
      hardConstraints: [
        "Sensitivity for life-critical conditions must meet clinical safety minimum (>98%)",
        "Feature selection must respect clinical interpretability and causal plausibility",
        "Algorithm must output calibrated diagnostic confidence and uncertainty intervals",
        "Execution latency per patient record cannot exceed operational clinical SLA",
        "Model must not collapse under missing or asynchronously sampled clinical inputs",
      ],
      optimizationObjectives: [
        "Maximize diagnostic ROC-AUC and high-risk case recall",
        "Minimize false alarms and unnecessary clinical interventions",
        "Minimize computational complexity for edge clinical deployment",
        "Maximize stability and consistency across multi-center demographic shifts",
      ],
      hiddenTestNote: "Hidden test cases inject rare co-morbidities and 20% corrupted sensor telemetry. The model must preserve life-critical sensitivity.",
      expectedOutputChecklist: EXPECTED_OUTPUT_CHECKLIST,
      description: "Develop AI and machine-learning solutions for healthcare, including disease prediction, clinical decision support, and personalized medicine.",
      statementMarkdown: `### Theme 1 — Biomedical Artificial Intelligence\n\n**Society:** IEEE EMBS × IEEE CIS | **Track:** Advanced | **Technique:** Evolutionary Neural Architecture Search & Hybrid GA-ML\n\n#### Context\nClinical healthcare pipelines generate vast multi-modal patient telemetry, electronic health records, genomic biomarkers, and pathology features. Medical practitioners require explainable AI models capable of predictive risk stratification while respecting strict sensitivity constraints.\n\n#### Core Challenge\nDesign an evolutionary optimization algorithm to search high-dimensional biomedical feature spaces and optimize hybrid clinical decision boundaries, maximizing sensitivity for rare critical pathologies while minimizing false positive alerts under real-world clinical noise.`,
      starterNotebookUrl: "/starter/starter_p1_scheduling.py",
      benchmarkType: "BIOMEDICAL_AI_EVOLUTIONARY",
      hiddenShiftAttempt2: "Demographic perturbation: Patient age and comorbid distributions shifted by 35% with missing laboratory markers.",
      hiddenShiftAttempt3: "Adversarial clinical noise: 20% of continuous ICU vitals perturbed with Gaussian sensor drift.",
      livePatchSurprise: "One urgent biomarker feature is rendered unavailable; algorithm must dynamically re-evaluate confidence without retraining from scratch.",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "theme-2-signals",
      name: "Biomedical Signals & Intelligent Systems",
      shortName: "02: Biomedical Signals",
      society: "IEEE EMBS",
      difficulty: "Advanced",
      technique: "Fuzzy Inference Systems + Evolutionary Signal Decomposition",
      context: "Continuous physiological monitoring in Intensive Care Units captures streaming ECG, EMG, and photoplethysmography (PPG) waveforms subject to severe motion artifacts and baseline wandering.",
      coreChallenge: "Formulate an evolutionary fuzzy system that filters non-stationary artifacts, extracts morphological signal components, and detects acute cardiac or neurological events with high fidelity and ultra-low latency.",
      hardConstraints: [
        "Real-time streaming throughput must match patient monitor sampling rates (>500 Hz)",
        "Critical cardiac events (ventricular fibrillation, asystole) must trigger alerts within 2 seconds",
        "Fuzzy membership rules must adhere to established clinical cardiology guidelines",
        "Processing pipeline must preserve morphological diagnostic peaks (QRS complexes, P waves)",
        "Filter coefficients must maintain phase linearity without introducing latency distortion",
      ],
      optimizationObjectives: [
        "Minimize ICU monitor false alarm rate by >70% while preserving 100% true event sensitivity",
        "Maximize signal-to-noise ratio (SNR) improvement across noisy leads",
        "Minimize computational footprint for wearable battery-powered cardiac patches",
        "Maximize adaptability across diverse baseline physiological variations",
      ],
      hiddenTestNote: "Hidden test cases inject severe electrosurgical cautery bursts and motion-induced baseline wandering.",
      expectedOutputChecklist: EXPECTED_OUTPUT_CHECKLIST,
      description: "Apply intelligent algorithms to ECG, EEG, EMG, and PPG for signal processing, anomaly detection, and physiological monitoring.",
      statementMarkdown: `### Theme 2 — Biomedical Signals & Intelligent Systems\n\n**Society:** IEEE EMBS | **Track:** Advanced | **Technique:** Fuzzy Inference Systems + Evolutionary Signal Decomposition\n\n#### Context\nContinuous physiological monitoring in Intensive Care Units captures streaming ECG, EMG, and photoplethysmography (PPG) waveforms subject to severe motion artifacts and baseline wandering.\n\n#### Core Challenge\nFormulate an evolutionary fuzzy system that filters non-stationary artifacts, extracts morphological signal components, and detects acute cardiac or neurological events with high fidelity and ultra-low latency.`,
      starterNotebookUrl: "/starter/starter_p6_triage.py",
      benchmarkType: "BIOMEDICAL_SIGNALS_EVOLUTIONARY_FUZZY",
      hiddenShiftAttempt2: "Motion artifact injection: High-amplitude respiratory baseline wander superimposed on Lead II.",
      hiddenShiftAttempt3: "Ectopic beat clustering: Premature ventricular contractions (PVCs) occurring in rapid trigeminy bursts.",
      livePatchSurprise: "One lead disconnects entirely; system must reconstruct cardiac rhythm from single remaining PPG sensor.",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "theme-3-imaging",
      name: "Medical Imaging & Computer Vision",
      shortName: "03: Medical Imaging",
      society: "IEEE EMBS",
      difficulty: "Advanced",
      technique: "Genetic Algorithms + Heuristic Feature Space Search",
      context: "Clinical diagnosis from MRI, CT, and histological scans is hindered by low contrast, sensor noise, and artifact occlusions. Accurate boundary delineation of pathological lesions is vital.",
      coreChallenge: "Engineer a genetic heuristic that optimizes multi-scale feature filters, deformable contour boundaries, and spatial segmentation masks to maximize lesion detection precision under severe class imbalance and scan noise.",
      hardConstraints: [
        "False negative rate on malignant findings must remain below clinical safety limits",
        "Geometric contours must maintain anatomical boundary continuity and smoothness",
        "Volumetric reconstruction must execute within clinical emergency turnaround budgets",
        "Algorithm must demonstrate invariance to scan orientation and slice thickness variations",
        "All segmentations must generate pixel-level confidence maps for radiologist review",
      ],
      optimizationObjectives: [
        "Maximize Dice similarity coefficient and IoU on lesion target regions",
        "Minimize boundary Hausdorff distance and false positive segmentations",
        "Minimize computational runtime and peak memory usage",
        "Maximize robustness against motion blur, metallic artifacts, and low SNR",
      ],
      hiddenTestNote: "Hidden test cases introduce low-dose ultra-noisy scans and small boundary-adjacent micro-calcifications.",
      expectedOutputChecklist: EXPECTED_OUTPUT_CHECKLIST,
      description: "Develop intelligent systems for MRI, CT, ultrasound, and histopathological image analysis, segmentation, and automated interpretation.",
      statementMarkdown: `### Theme 3 — Medical Imaging & Computer Vision\n\n**Society:** IEEE EMBS | **Track:** Advanced | **Technique:** Genetic Algorithms + Heuristic Feature Space Search\n\n#### Context\nClinical diagnosis from MRI, CT, and histological scans is hindered by low contrast, sensor noise, and artifact occlusions. Accurate boundary delineation of pathological lesions is vital.\n\n#### Core Challenge\nEngineer a genetic heuristic that optimizes multi-scale feature filters, deformable contour boundaries, and spatial segmentation masks to maximize lesion detection precision under severe class imbalance and scan noise.`,
      starterNotebookUrl: "/starter/starter_p5_swarm.py",
      benchmarkType: "MEDICAL_IMAGING_HEURISTIC_SEARCH",
      hiddenShiftAttempt2: "Low-dose scan noise: SNR reduced by 50% with metallic dental implant streak artifacts.",
      hiddenShiftAttempt3: "Micro-lesion challenge: Target pathology diameter reduced to sub-voxel resolution (<3mm).",
      livePatchSurprise: "Slice thickness increased by 4x; algorithm must infer 3D contours without volumetric slice re-interpolation.",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "theme-4-ml-ai",
      name: "Machine Learning & Artificial Intelligence",
      shortName: "04: ML & Artificial Intelligence",
      society: "IEEE CIS",
      difficulty: "Intermediate–Advanced",
      technique: "Multi-Objective Heuristics + Deep Evolutionary Networks",
      context: "Intelligent systems operating in dynamic real-world environments require adaptive learning models capable of solving complex multi-modal classification, continuous regression, and generative modeling tasks.",
      coreChallenge: "Design a high-performance machine learning optimization model combining automated hyperparameter search with robust loss regularization to generalize across non-stationary distributions.",
      hardConstraints: [
        "Generalization bounds must hold across out-of-distribution validation sets",
        "Optimization trajectory must converge deterministically without gradient explosion",
        "Model parameter efficiency must adhere to runtime deployment budgets",
        "Decision outputs must satisfy fair calibration across heterogeneous sub-populations",
      ],
      optimizationObjectives: [
        "Maximize multi-metric validation accuracy and generalized predictive capability",
        "Minimize loss variance and over-fitting penalty across unseen held-out splits",
        "Minimize inference latency and computational overhead",
        "Maximize explainability and architectural stability",
      ],
      hiddenTestNote: "Hidden scenarios test generalization across non-stationary dataset drift and noisy label corruptions.",
      expectedOutputChecklist: EXPECTED_OUTPUT_CHECKLIST,
      description: "Explore machine learning, deep learning, generative AI, and intelligent algorithms for solving complex real-world problems.",
      statementMarkdown: `### Theme 4 — Machine Learning & Artificial Intelligence\n\n**Society:** IEEE CIS | **Track:** Intermediate–Advanced | **Technique:** Multi-Objective Heuristics + Deep Evolutionary Networks\n\n#### Context\nIntelligent systems operating in dynamic real-world environments require adaptive learning models capable of solving complex multi-modal classification, continuous regression, and generative modeling tasks.\n\n#### Core Challenge\nDesign a high-performance machine learning optimization model combining automated hyperparameter search with robust loss regularization to generalize across non-stationary distributions.`,
      starterNotebookUrl: "/starter/starter_p2_drone.py",
      benchmarkType: "EDTECH_KNOWLEDGE_SPACE_GA",
      hiddenShiftAttempt2: "Non-stationary distribution shift: 35% covariate drift injected into held-out evaluation splits.",
      hiddenShiftAttempt3: "Adversarial noise injection: Feature space perturbed with high-frequency noise bursts.",
      livePatchSurprise: "Regularization penalty doubled; model must maintain generalization without retraining from scratch.",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "theme-5-autonomous",
      name: "Intelligent Systems & Autonomous Computing",
      shortName: "05: Autonomous Systems",
      society: "IEEE CIS",
      difficulty: "Advanced",
      technique: "Swarm Intelligence + Adaptive Multi-Agent Heuristics",
      context: "Decentralized autonomous agents operating in shared environments must coordinate navigation, resource allocation, and distributed task execution under communication constraints and unpredictable hazards.",
      coreChallenge: "Engineer a multi-agent autonomous decision-making engine that coordinates agent trajectories, resolves resource contention, and dynamically plans pathing under real-time environmental perturbations.",
      hardConstraints: [
        "Agents must guarantee collision-free trajectories and safe operational margins",
        "Decision latency per simulation tick must stay strictly within real-time budget",
        "Coordination protocol must operate without centralized single-point-of-failure bottlenecks",
        "Dynamic environment changes must trigger sub-second trajectory recalibration",
      ],
      optimizationObjectives: [
        "Maximize collective swarm task throughput and coverage velocity",
        "Minimize cumulative collision risk and coordination deadlocks",
        "Minimize energy consumption and path trajectory length",
        "Maximize resilience against individual agent failures or communication dropouts",
      ],
      hiddenTestNote: "Hidden evaluation scenarios introduce corridor blockages and sudden network communication dropouts.",
      expectedOutputChecklist: EXPECTED_OUTPUT_CHECKLIST,
      description: "Develop autonomous, adaptive, and multi-agent systems capable of intelligent decision-making, learning, and real-time operation.",
      statementMarkdown: `### Theme 5 — Intelligent Systems & Autonomous Computing\n\n**Society:** IEEE CIS | **Track:** Advanced | **Technique:** Swarm Intelligence + Adaptive Multi-Agent Heuristics\n\n#### Context\nDecentralized autonomous agents operating in shared environments must coordinate navigation, resource allocation, and distributed task execution under communication constraints and unpredictable hazards.\n\n#### Core Challenge\nEngineer a multi-agent autonomous decision-making engine that coordinates agent trajectories, resolves resource contention, and dynamically plans pathing under real-time environmental perturbations.`,
      starterNotebookUrl: "/starter/starter_p4_grid.py",
      benchmarkType: "HEALTHCARE_ROBOTICS_SWARM",
      hiddenShiftAttempt2: "Network drop: 30% of multi-agent communication links intermittently disrupted.",
      hiddenShiftAttempt3: "Corridor blockade: Primary throughput corridors obstructed by dynamic hazard objects.",
      livePatchSurprise: "Agent battery speed clamped to 50%; swarm must recalibrate rendezvous points within 15 minutes.",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "theme-6-open-innovation",
      name: "Open Innovation: CIS × EMBS",
      shortName: "06: Open Innovation",
      society: "IEEE CIS & IEEE EMBS Only",
      difficulty: "Advanced",
      technique: "Hybrid Computational Intelligence & Novel Metaheuristics",
      context: "The frontier of medical technology demands unconventional computational intelligence methodologies uniting biological modeling with cutting-edge algorithmic optimization.",
      coreChallenge: "Architect an original computational intelligence solution solving an unaddressed cross-disciplinary challenge spanning biomedical engineering and computational intelligence theory.",
      hardConstraints: [
        "Proposed algorithmic architecture must combine both EMBS and CIS core tenets",
        "Solutions must be accompanied by rigorous mathematical formulation and code harness",
        "Computational complexity must scale tractably with real-world clinical datasets",
        "All third-party scientific baselines and data sources must be credited and reproducible",
      ],
      optimizationObjectives: [
        "Maximize algorithmic novelty, cross-domain ingenuity, and mathematical elegance",
        "Maximize empirical performance gain over standard industry benchmark baselines",
        "Maximize clinical applicability and translational potential in healthcare settings",
        "Maximize computational execution efficiency and parameter sensitivity robustness",
      ],
      hiddenTestNote: "Judges evaluate algorithmic robustness against custom unannounced perturbation test suites.",
      expectedOutputChecklist: EXPECTED_OUTPUT_CHECKLIST,
      description: "An interdisciplinary track for novel solutions combining computational intelligence with biomedical engineering and healthcare challenges.",
      statementMarkdown: `### Theme 6 — Open Innovation: CIS × EMBS\n\n**Society:** IEEE CIS & IEEE EMBS Only | **Track:** Advanced | **Technique:** Hybrid Computational Intelligence & Novel Metaheuristics\n\n#### Context\nThe frontier of medical technology demands unconventional computational intelligence methodologies uniting biological modeling with cutting-edge algorithmic optimization.\n\n#### Core Challenge\nArchitect an original computational intelligence solution solving an unaddressed cross-disciplinary challenge spanning biomedical engineering and computational intelligence theory.`,
      starterNotebookUrl: "/starter/starter_p3_hospital.py",
      benchmarkType: "OPEN_INNOVATION_CIS_EMBS",
      hiddenShiftAttempt2: "Constraint stress test: Penalty multiplier for constraint violations doubled in evaluation harness.",
      hiddenShiftAttempt3: "Generalization challenge: Objective function tested against unseen higher-dimensional parameter space.",
      livePatchSurprise: "Defend and modify algorithmic fitness function live before judges under 15-minute countdown.",
      createdAt: now,
      updatedAt: now,
    },
  ];

  // 3. Admin & Judge Accounts for all 9 Innovation Themes
  const adminPassword = await bcrypt.hash("admin@optiforge2026", 10);
  const judgePassword = await bcrypt.hash("judge@optiforge2026", 10);

  const users = [
    {
      id: crypto.randomUUID(),
      username: "admin",
      password: adminPassword,
      name: "Lead Organizer (IEEE EMBS × CIS)",
      role: "ADMIN",
      assignedDomainId: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: crypto.randomUUID(),
      username: "judge_t1",
      password: judgePassword,
      name: "Dr. K. Srinivas (Biomedical AI & Neural Opt Expert)",
      role: "JUDGE",
      assignedDomainId: "theme-1-biomedical-ai",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: crypto.randomUUID(),
      username: "judge_t2",
      password: judgePassword,
      name: "Prof. S. Reddy (Biomedical Signals & ECG/EEG Expert)",
      role: "JUDGE",
      assignedDomainId: "theme-2-signals",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: crypto.randomUUID(),
      username: "judge_t3",
      password: judgePassword,
      name: "Dr. A. Sharma (Medical Imaging & Computer Vision Expert)",
      role: "JUDGE",
      assignedDomainId: "theme-3-imaging",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: crypto.randomUUID(),
      username: "judge_t4",
      password: judgePassword,
      name: "Prof. M. Anitha (Machine Learning & AI Theory Expert)",
      role: "JUDGE",
      assignedDomainId: "theme-4-ml-ai",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: crypto.randomUUID(),
      username: "judge_t5",
      password: judgePassword,
      name: "Dr. T. Patel (Intelligent Systems & Autonomous Computing Expert)",
      role: "JUDGE",
      assignedDomainId: "theme-5-autonomous",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: crypto.randomUUID(),
      username: "judge_t6",
      password: judgePassword,
      name: "Dr. N. Gupta (CIS & EMBS Open Innovation Jury Chair)",
      role: "JUDGE",
      assignedDomainId: "theme-6-open-innovation",
      createdAt: now,
      updatedAt: now,
    },
  ];

  // 4. Official Registered Teams (Preserving verified credentials)
  const password2402 = await bcrypt.hash("Forge#2402", 10);
  const password1904 = await bcrypt.hash("Forge#1904", 10);
  const password3340 = await bcrypt.hash("Forge#3340", 10);
  const password7902 = await bcrypt.hash("Forge#7902", 10);
  const password7151 = await bcrypt.hash("Forge#7151", 10);
  const password1112 = await bcrypt.hash("Forge#1112", 10);

  const teamsData = [
    {
      id: "98422411-03e4-4ce0-842e-4ec73077014c",
      teamCode: "OPT-26-2402",
      teamName: "jiva jhanavi tirupati",
      leaderEmail: "hvhv@gvj.djb",
      leaderPhone: "9876543218",
      password: password2402,
      domainId: "theme-6-open-innovation",
      skillLevel: "Standard",
      paymentStatus: "CONFIRMED",
      paymentAmount: 300,
      razorpayPaymentId: "987653234567",
      razorpayOrderId: "order_upi_987653234567",
      razorpaySignature: "UPI_DIRECT_SETTLEMENT",
      attemptsUsed: 2,
      bestScore: 66.55,
      isDisqualified: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "team-id-1904",
      teamCode: "OPT-26-1904",
      teamName: "Team 1904",
      leaderEmail: "chair.embs@vce.ac.in",
      leaderPhone: "9490298994",
      password: password1904,
      domainId: "theme-1-biomedical-ai",
      skillLevel: "Standard",
      paymentStatus: "CONFIRMED",
      paymentAmount: 150,
      razorpayPaymentId: "512165830063",
      razorpayOrderId: "order_upi_512165830063",
      razorpaySignature: "UPI_DIRECT_SETTLEMENT",
      attemptsUsed: 0,
      bestScore: 0,
      isDisqualified: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "46e71909-db45-428a-8717-0f1aa94bab89",
      teamCode: "OPT-26-3340",
      teamName: "I'm Game",
      leaderEmail: "msteja@gmail.com",
      leaderPhone: "9633428107",
      password: password3340,
      domainId: "theme-2-signals",
      skillLevel: "Standard",
      paymentStatus: "CONFIRMED",
      paymentAmount: 100,
      razorpayPaymentId: "786622855890",
      razorpayOrderId: "order_upi_786622855890",
      razorpaySignature: "UPI_DIRECT_SETTLEMENT",
      attemptsUsed: 0,
      bestScore: 0,
      isDisqualified: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "5e139fb9-3cbe-40d9-941a-0c3eef3819c0",
      teamCode: "OPT-26-7902",
      teamName: "test",
      leaderEmail: "dfgf@gtf.jub",
      leaderPhone: "9234567890",
      password: password7902,
      domainId: "theme-1-biomedical-ai",
      skillLevel: "Standard",
      paymentStatus: "CONFIRMED",
      paymentAmount: 100,
      razorpayPaymentId: "123456766666",
      razorpayOrderId: "order_upi_123456766666",
      razorpaySignature: "UPI_DIRECT_SETTLEMENT",
      attemptsUsed: 0,
      bestScore: 0,
      isDisqualified: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "team-id-7151",
      teamCode: "OPT-26-7151",
      teamName: "Team 7151",
      leaderEmail: "team7151@vce.ac.in",
      leaderPhone: "9490298994",
      password: password7151,
      domainId: "theme-1-biomedical-ai",
      skillLevel: "Standard",
      paymentStatus: "PENDING_PAYMENT",
      paymentAmount: 150,
      razorpayPaymentId: null,
      razorpayOrderId: null,
      razorpaySignature: null,
      attemptsUsed: 0,
      bestScore: 0,
      isDisqualified: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "team-id-1112",
      teamCode: "OPT-26-1112",
      teamName: "Team 1112",
      leaderEmail: "team1112@vce.ac.in",
      leaderPhone: "9490298994",
      password: password1112,
      domainId: "theme-1-biomedical-ai",
      skillLevel: "Standard",
      paymentStatus: "PENDING_PAYMENT",
      paymentAmount: 150,
      razorpayPaymentId: null,
      razorpayOrderId: null,
      razorpaySignature: null,
      attemptsUsed: 0,
      bestScore: 0,
      isDisqualified: false,
      createdAt: now,
      updatedAt: now,
    },
  ];

  const teamMembers = [
    {
      id: crypto.randomUUID(),
      teamId: "98422411-03e4-4ce0-842e-4ec73077014c",
      name: "Jiva Jhanavi Tirupati",
      collegeName: "Vardhaman College of Engineering",
      rollNumber: "22881A0521",
      branch: "CSE",
      year: "3rd Year",
      email: "hvhv@gvj.djb",
      phone: "9876543218",
      tshirtSize: null,
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      teamId: "98422411-03e4-4ce0-842e-4ec73077014c",
      name: "Member 2",
      collegeName: "Vardhaman College of Engineering",
      rollNumber: "22881A0522",
      branch: "CSE",
      year: "3rd Year",
      email: "member2_2402@vce.ac.in",
      phone: "9876543219",
      tshirtSize: null,
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      teamId: "98422411-03e4-4ce0-842e-4ec73077014c",
      name: "Member 3",
      collegeName: "Vardhaman College of Engineering",
      rollNumber: "22881A0523",
      branch: "ECE",
      year: "3rd Year",
      email: "member3_2402@vce.ac.in",
      phone: "9876543220",
      tshirtSize: null,
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      teamId: "46e71909-db45-428a-8717-0f1aa94bab89",
      name: "M. Sai Teja",
      collegeName: "Vardhaman College of Engineering",
      rollNumber: "22881A0531",
      branch: "CSE",
      year: "3rd Year",
      email: "msteja@gmail.com",
      phone: "9633428107",
      tshirtSize: null,
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      teamId: "46e71909-db45-428a-8717-0f1aa94bab89",
      name: "Member 2",
      collegeName: "Vardhaman College of Engineering",
      rollNumber: "22881A0532",
      branch: "ECE",
      year: "3rd Year",
      email: "member2_3340@vce.ac.in",
      phone: "9633428108",
      tshirtSize: null,
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      teamId: "5e139fb9-3cbe-40d9-941a-0c3eef3819c0",
      name: "Test Leader",
      collegeName: "Vardhaman College of Engineering",
      rollNumber: "22881A0541",
      branch: "CSE",
      year: "3rd Year",
      email: "dfgf@gtf.jub",
      phone: "9234567890",
      tshirtSize: null,
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      teamId: "5e139fb9-3cbe-40d9-941a-0c3eef3819c0",
      name: "Member 2",
      collegeName: "Vardhaman College of Engineering",
      rollNumber: "22881A0542",
      branch: "IT",
      year: "3rd Year",
      email: "member2_7902@vce.ac.in",
      phone: "9234567891",
      tshirtSize: null,
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      teamId: "team-id-1904",
      name: "Maruthi Sai Teja",
      collegeName: "Vardhaman College of Engineering",
      rollNumber: "22881A0501",
      branch: "CSE",
      year: "3rd Year",
      email: "chair.embs@vce.ac.in",
      phone: "9490298994",
      tshirtSize: null,
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      teamId: "team-id-1904",
      name: "Sai Teja",
      collegeName: "Vardhaman College of Engineering",
      rollNumber: "22881A0502",
      branch: "CSE",
      year: "3rd Year",
      email: "saiteja.dev@vce.ac.in",
      phone: "9490298995",
      tshirtSize: null,
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      teamId: "team-id-1904",
      name: "K. Rithvik",
      collegeName: "Vardhaman College of Engineering",
      rollNumber: "22881A0503",
      branch: "IT",
      year: "3rd Year",
      email: "rithvik.k@vce.ac.in",
      phone: "9490298996",
      tshirtSize: null,
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      teamId: "team-id-7151",
      name: "Team Leader",
      collegeName: "Vardhaman College of Engineering",
      rollNumber: "22881A0511",
      branch: "CSE",
      year: "3rd Year",
      email: "team7151@vce.ac.in",
      phone: "9490298994",
      tshirtSize: null,
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      teamId: "team-id-7151",
      name: "Member 2",
      collegeName: "Vardhaman College of Engineering",
      rollNumber: "22881A0512",
      branch: "CSE",
      year: "3rd Year",
      email: "member2_7151@vce.ac.in",
      phone: "9490298995",
      tshirtSize: null,
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      teamId: "team-id-7151",
      name: "Member 3",
      collegeName: "Vardhaman College of Engineering",
      rollNumber: "22881A0513",
      branch: "IT",
      year: "3rd Year",
      email: "member3_7151@vce.ac.in",
      phone: "9490298996",
      tshirtSize: null,
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      teamId: "team-id-1112",
      name: "Team Leader",
      collegeName: "Vardhaman College of Engineering",
      rollNumber: "22881A0501",
      branch: "CSE",
      year: "3rd Year",
      email: "team1112@vce.ac.in",
      phone: "9490298994",
      tshirtSize: null,
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      teamId: "team-id-1112",
      name: "Member 2",
      collegeName: "Vardhaman College of Engineering",
      rollNumber: "22881A0502",
      branch: "CSE",
      year: "3rd Year",
      email: "member2_1112@vce.ac.in",
      phone: "9490298995",
      tshirtSize: null,
      createdAt: now,
    },
    {
      id: crypto.randomUUID(),
      teamId: "team-id-1112",
      name: "Member 3",
      collegeName: "Vardhaman College of Engineering",
      rollNumber: "22881A0503",
      branch: "IT",
      year: "3rd Year",
      email: "member3_1112@vce.ac.in",
      phone: "9490298996",
      tshirtSize: null,
      createdAt: now,
    },
  ];

  const submissions = [];
  const judgeEvaluations = [];

  const announcements = [
    {
      id: "ann-1",
      title: "Welcome to OptiForge 2026 — Registration Now Open",
      message: "Registrations are actively underway across Telangana and Andhra Pradesh. Prepare your teams for the live Hackathon Algorithm Design on 30-09-2026 (10:00 AM - 4:00 PM IST).",
      type: "INFO",
      isActive: true,
      createdAt: now,
    },
  ];

  const dbData = {
    users,
    teams: teamsData,
    teamMembers,
    problemTracks,
    submissions,
    judgeEvaluations,
    announcements,
    systemSettings,
    auditLogs: [
      {
        id: crypto.randomUUID(),
        action: "PAYMENT_CONFIRMED",
        performedBy: "chair.embs@vce.ac.in",
        details: "Direct UPI Payment of ₹150 verified for Team 1904 (OPT-26-1904). 12-digit UTR: 512165830063. Payee: Maruthi Sai Teja (9490298994@axl)",
        reason: "Direct UPI Transfer (Verified)",
        createdAt: now,
      },
      {
        id: crypto.randomUUID(),
        action: "DATABASE_INITIALIZED",
        performedBy: "system",
        details: "OptiForge 2026 initialized with 9 official innovation themes and 9 expert domain judges",
        reason: "Official Hackathon Algorithm Design release",
        createdAt: now,
      },
    ],
  };

  fs.writeFileSync(DB_FILE, JSON.stringify(dbData, null, 2), "utf8");
  console.log("Database seeded successfully with 9 innovation themes to:", DB_FILE);
}

seed().catch((err) => {
  console.error("Seeding failed:", err);
  process.exit(1);
});
